# Generated by Django 5.0 on 2024-11-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=160)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('concluido', models.BooleanField()),
            ],
        ),
    ]
