# Generated by Django 5.0 on 2024-11-19 22:32

import tarefas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=tarefas.models.upload_foto),
        ),
    ]
